name: Generate HTML and PDFs from Markdown
on:
  push:
    paths:
      - '**/*.md'
      - '.github/workflows/generate-html-pdfs.yml'
      - 'scripts/**/*'
    branches-ignore:
      - gh-pages
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-html:
    name: Generate HTML artifacts
    runs-on: ubuntu-latest
    outputs:
      html: ${{ steps.set-matrix.outputs.html }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build HTML
        shell: bash
        run: |
          shopt -s globstar
          pip install -r scripts/requirements.txt
          scripts/mds_to_html.sh

      - name: Upload HTML artifact
        uses: actions/upload-artifact@v4
        with:
          path: build
          name: html-build

      - name: Enumerate HTML files
        id: set-matrix
        run: |
          shopt -s globstar
          {
            echo 'html<<EOF'
            ls -1 build/**/*.html | jq -R -s -c 'split("\n")[:-1]'
            echo EOF
          } >> "$GITHUB_OUTPUT"

  publish-pages:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs: [generate-html]

    steps:
      - name: Checkout GitHub Pages
        continue-on-error: true
        id: checkout
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Create new gh-pages branch
        shell: bash
        if: steps.checkout.outcome == 'failure'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
          git checkout --orphan gh-pages
          git reset --hard
          git commit --allow-empty -m "Initial gh-pages commit"

      - name: Download HTML artifact
        uses: actions/download-artifact@v4
        with:
          path: build
          name: html-build

      - name: Commit artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
          MAIN: ${{ github.event.repository.default_branch }}
          OWNER: ${{ github.event.repository.owner.login }}
          REPO: ${{ github.event.repository.name }}
        run: |
          shopt -s globstar
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
          # HACK: patch absolute URLs to web root
          if [ "$BRANCH" != "$MAIN" ]; then
            # Trailing slash is important!
            SUBDIR="branch/$BRANCH/"
            mkdir -p "$SUBDIR"
          else
            SUBDIR=""
          fi
          cp -rf build/* "./$SUBDIR"
          rm -rf build
          if [ "$REPO" == "$OWNER.github.io" ]; then
            BASE="/"
          else
            BASE="/$REPO/"
          fi
          for f in ./$SUBDIR/**/*.html; do
            sed -i -re "s#(href|src)=\"/([^\"]*)\"#\1=\"$BASE$SUBDIR\2\"#" "$f"
          done
          if [ -z "$SUBDIR" ]; then
            git restore branch/**/*
          fi
          git add **/*.{html,css,js} **/images
          if [ -z "$(git status --porcelain=2)" ]; then
            echo "Nothing to commit; exiting cleanly"
            exit 0
          fi
          git commit -m "Generate HTML from commit $GITHUB_SHA"
          git push -u origin gh-pages

  generate-pdfs:
    name: Generate PDF build
    runs-on: ubuntu-latest
    needs: [generate-html]
    strategy:
      fail-fast: true
      matrix:
        file: ${{ fromJson(needs.generate-html.outputs.html) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download HTML artifact
        uses: actions/download-artifact@v4
        with:
          name: html-build
          path: build

      - name: Get PDF filename
        shell: bash
        id: pdf
        env:
          FILE: ${{ matrix.file }}
        run: |
          cat "$FILE" | sed -r -n -e 's/^.*<!--\s*title:\s*(.+)$/file=\1.pdf/p' >> "$GITHUB_OUTPUT"
          echo "$FILE" | sed -r 's/ /-/g;s/[^a-zA-Z0-9_-]+/-/g;s/(.+)/artifact=\L\1/g' >> "$GITHUB_OUTPUT"

      - name: Prepare directory structure
        shell: bash
        env:
          HTML_FILE: ${{ matrix.file }}
          PDF_FILE: ${{ steps.pdf.outputs.file }}
        run: |
          mv -f "$HTML_FILE" build/index.html || echo No need to move index
          mkdir -p build/pdf/$(dirname "$PDF_FILE")

      - name: Generate PDF from HTML
        uses: ferdinandkeller/html-to-pdf-action@v2.1
        with:
          source-path: "./build"
          destination-path: "./build/pdf/${{ steps.pdf.outputs.file }}"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/pdf
          name: pdf-out-${{ steps.pdf.outputs.artifact }}

  commit-pdfs:
    name: Commit and push PDFs
    runs-on: ubuntu-latest
    needs: [generate-pdfs]
    if: github.ref_name == github.event.repository.default_branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download PDF artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: pdf-out-*
          merge-multiple: true

      - name: Commit and push PDFs
        shell: bash
        run: |
          shopt -s globstar
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR_ID+$GITHUB_ACTOR@users.noreply.github.com"
          git add **/*.pdf
          if [ -z "$(git status --porcelain=2)" ]; then
            echo "Nothing to commit; exiting cleanly"
            exit 0
          fi
          git commit -m "Generate PDFs from commit $GITHUB_SHA"
          git push
