name: Comment GitHub Pages link on new pull requests
on:
  pull_request_target:
    paths:
      - '**/*.md'
      - '.github/workflows/generate-html-pdfs.yml'
      - 'scripts/**/*'
    branches-ignore:
      - gh-pages
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  link-html:
    name: Post link to GitHub Pages build
    runs-on: ubuntu-latest

    steps:
      - name: Post link
        uses: actions/github-script@v7
        env:
          OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
          REPO: ${{ github.event.pull_request.head.repo.name }}
          HEAD: ${{ github.head_ref }}
          URL: ${{ github.event.pull_request.html_url }}/files
        with:
          script: |
            let {data: {html_url: url}} = await github.rest.repos.getPages({
              owner: process.env.OWNER,
              repo: process.env.REPO,
            });
            if (process.env.HEAD != 'master') {
              url += `branch/${process.env.HEAD}`;
            }
            const diff_url = process.env.URL;
            const body = `Please remember to check [the diff](${diff_url}) for
            reference warnings. Successful HTML builds will appear at ${url}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
