name: Comment section-by-section diff on new pull requests
on:
  pull_request_target:
    paths:
      - '**/*.md'
      - '!**/README.md'
      - '!**/LICENSE*'
    branches-ignore:
      - gh-pages

permissions:
  issues: write
  pull-requests: write

jobs:
  comment-diff:
    name: Post human-readable diff
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: (DANGER!) Checkout head
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Run base version of diff scripts
        id: diff
        shell: bash
        env:
          BASE: ${{ github.event.pull_request.base.sha }}
        run: |
          shopt -s globstar
          git checkout "$BASE" -- '*.py' scripts/requirements.txt
          pip install -r scripts/requirements.txt
          {
            echo 'ghmd<<EOF'
            git diff --diff-filter=ad -U1000000 "$BASE" HEAD -- '*.md' | python scripts/diff_to_table.py del ins
            echo EOF
          } >> "$GITHUB_OUTPUT"
          {
            echo 'gdmd<<EOF'
            git diff --diff-filter=ad -U1000000 "$BASE" HEAD -- '*.md' | python scripts/diff_to_table.py s u
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Post diff
        uses: actions/github-script@v7
        env:
          BODY: |
            ## Section-by-section diff

            <details>
            <summary>Full table of differences</summary>

            ${{ steps.diff.outputs.ghmd }}

            </details>

            <details>
            <summary>Markdown source of the table for copying into Google Docs</summary>

            ```md
            ${{ steps.diff.outputs.gdmd }}
            ```

            </details>
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.BODY
            });
