name: Annotate pull requests with crossref checks
on:
  pull_request:
    paths:
      - '**/*.md'
      - '!**/README.md'
      - '!**/LICENSE*'
    branches-ignore:
      - gh-pages

jobs:
  make-crossref:
    name: Annotate PR diff
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate annotations
        shell: bash
        env:
          BASE: ${{ github.event.pull_request.base.sha }}
        run: |
          shopt -s globstar
          pip install -r scripts/requirements.txt
          git diff --diff-filter=ad -U1000000 "$BASE" HEAD -- '*.md' | python scripts/diff_to_annotations.py
